# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import db_pb2 as db__pb2

GRPC_GENERATED_VERSION = '1.64.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in db_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class dbStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateNewUser = channel.unary_unary(
                '/db/CreateNewUser',
                request_serializer=db__pb2.DBRequestCreateNewUser.SerializeToString,
                response_deserializer=db__pb2.DBResponseCreateNewUser.FromString,
                _registered_method=True)
        self.GetBalance = channel.unary_unary(
                '/db/GetBalance',
                request_serializer=db__pb2.DBRequestGetBalance.SerializeToString,
                response_deserializer=db__pb2.DBResponseGetBalance.FromString,
                _registered_method=True)
        self.SendMoney = channel.unary_unary(
                '/db/SendMoney',
                request_serializer=db__pb2.DBRequestSendMoney.SerializeToString,
                response_deserializer=db__pb2.DBResponseSendMoney.FromString,
                _registered_method=True)


class dbServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateNewUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBalance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendMoney(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_dbServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateNewUser': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateNewUser,
                    request_deserializer=db__pb2.DBRequestCreateNewUser.FromString,
                    response_serializer=db__pb2.DBResponseCreateNewUser.SerializeToString,
            ),
            'GetBalance': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBalance,
                    request_deserializer=db__pb2.DBRequestGetBalance.FromString,
                    response_serializer=db__pb2.DBResponseGetBalance.SerializeToString,
            ),
            'SendMoney': grpc.unary_unary_rpc_method_handler(
                    servicer.SendMoney,
                    request_deserializer=db__pb2.DBRequestSendMoney.FromString,
                    response_serializer=db__pb2.DBResponseSendMoney.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'db', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('db', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class db(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateNewUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/db/CreateNewUser',
            db__pb2.DBRequestCreateNewUser.SerializeToString,
            db__pb2.DBResponseCreateNewUser.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBalance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/db/GetBalance',
            db__pb2.DBRequestGetBalance.SerializeToString,
            db__pb2.DBResponseGetBalance.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendMoney(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/db/SendMoney',
            db__pb2.DBRequestSendMoney.SerializeToString,
            db__pb2.DBResponseSendMoney.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
