# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: db.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08\x64\x62.proto\"$\n\x16\x44\x42RequestCreateNewUser\x12\n\n\x02Id\x18\x01 \x01(\t\")\n\x17\x44\x42ResponseCreateNewUser\x12\x0e\n\x06Status\x18\x01 \x01(\x08\"!\n\x13\x44\x42RequestGetBalance\x12\n\n\x02Id\x18\x01 \x01(\t\"7\n\x14\x44\x42ResponseGetBalance\x12\x0e\n\x06Status\x18\x01 \x01(\x08\x12\x0f\n\x07\x42\x61lance\x18\x02 \x01(\x02\"D\n\x12\x44\x42RequestSendMoney\x12\n\n\x02Id\x18\x01 \x01(\t\x12\x13\n\x0bRecipientId\x18\x02 \x01(\t\x12\r\n\x05Money\x18\x03 \x01(\x05\"4\n\x13\x44\x42ResponseSendMoney\x12\x0e\n\x06Status\x18\x01 \x01(\x08\x12\r\n\x05\x45rror\x18\x02 \x01(\t2\xbb\x01\n\x02\x64\x62\x12\x42\n\rCreateNewUser\x12\x17.DBRequestCreateNewUser\x1a\x18.DBResponseCreateNewUser\x12\x39\n\nGetBalance\x12\x14.DBRequestGetBalance\x1a\x15.DBResponseGetBalance\x12\x36\n\tSendMoney\x12\x13.DBRequestSendMoney\x1a\x14.DBResponseSendMoneyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'db_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DBREQUESTCREATENEWUSER']._serialized_start=12
  _globals['_DBREQUESTCREATENEWUSER']._serialized_end=48
  _globals['_DBRESPONSECREATENEWUSER']._serialized_start=50
  _globals['_DBRESPONSECREATENEWUSER']._serialized_end=91
  _globals['_DBREQUESTGETBALANCE']._serialized_start=93
  _globals['_DBREQUESTGETBALANCE']._serialized_end=126
  _globals['_DBRESPONSEGETBALANCE']._serialized_start=128
  _globals['_DBRESPONSEGETBALANCE']._serialized_end=183
  _globals['_DBREQUESTSENDMONEY']._serialized_start=185
  _globals['_DBREQUESTSENDMONEY']._serialized_end=253
  _globals['_DBRESPONSESENDMONEY']._serialized_start=255
  _globals['_DBRESPONSESENDMONEY']._serialized_end=307
  _globals['_DB']._serialized_start=310
  _globals['_DB']._serialized_end=497
# @@protoc_insertion_point(module_scope)
